Repository zmynx/aws-lambda-calculator, pull requests merged in 2025-04, with the labels that each got.

#94 feat(coverage): added built-in to pytest
  .devcontainer/devcontainer.image.json
  .github/workflows/ci.yaml
  .github/workflows/coverage.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/unit-tests.yaml
  .gitignore
  aws-lambda-calculator/poetry.lock
  aws-lambda-calculator/pyproject.toml
  poetry.lock
  pyproject.toml
  sonar-project.properties
Labels: ci-cd, development, release, feature, Review effort 2/5

#96 Hotfix/distroless
  Containerfile
Labels: release

#97 fix: distroless
  .github/workflows/cd-image.yaml
  .github/workflows/ci.yaml
  .github/workflows/unit-tests.yaml
Labels: ci-cd, release, Review effort 2/5

#98 Hotfix/distroless
  Containerfile
Labels: ci-cd, release, Review effort 2/5

#99 fix(dependabot): remove license "file" call to solve dependabot issues
  aws-lambda-calculator/poetry.lock
  aws-lambda-calculator/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: development, release, Review effort 1/5

#109 feat: runs-on
  .github/workflows/runs-on.yaml
Labels: ci-cd, release, feature, Review effort 1/5

#110 feat: aws-codebuild
  .github/workflows/aws-codebuild.yaml
Labels: ci-cd, release, feature, Review effort 1/5

#117 fix: build-api
  aws-lambda-calculator/poetry.lock
  aws-lambda-calculator/pyproject.toml
  aws-lambda-calculator/src/aws_lambda_calculator/calculator.py
Labels: release, feature, Review effort 1/5

#106 feat: seperated justfiles
  .devcontainer/devcontainer.json
  .justfile
  aws-lambda-calculator/.justfile
  justfiles/cosign.just
  justfiles/podman.just
  justfiles/poetry.just
  justfiles/superlinter.just
  justfiles/trivy.just
Labels: ci-cd, release, feature, Review effort 2/5

#107 feat: coverage
  .direnv/flake-profile
  .direnv/flake-profile-1-link
  .github/workflows/integration-tests.yaml
  .github/workflows/unit-tests.yaml
Labels: ci-cd, development, release, feature, Review effort 2/5

#111 fix: push trigger is essential
  .github/workflows/code-checks.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/unit-tests.yaml
  .python-version
  aws-lambda-calculator/.python-version
  poetry.lock
Labels: ci-cd, development, release, feature, Review effort 1/5
